[package]
name = "savefile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = {version="3.1.6", features=["derive"]}
flate2 = "1.0.22"
tar = "0.4.38"
